// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: assetstreamer.proto
#ifndef GRPC_assetstreamer_2eproto__INCLUDED
#define GRPC_assetstreamer_2eproto__INCLUDED

#include "assetstreamer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

// The asset streamer service definition.
class AssetStreamer final {
 public:
  static constexpr char const* service_full_name() {
    return "AssetStreamer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Requests for an Asset
    virtual ::grpc::Status RequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::Asset* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Asset>> AsyncRequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Asset>>(AsyncRequestAssetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Asset>> PrepareAsyncRequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Asset>>(PrepareAsyncRequestAssetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Requests for an Asset
      virtual void RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Asset>* AsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Asset>* PrepareAsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::Asset* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Asset>> AsyncRequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Asset>>(AsyncRequestAssetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Asset>> PrepareAsyncRequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Asset>>(PrepareAsyncRequestAssetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, std::function<void(::grpc::Status)>) override;
      void RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Asset>* AsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Asset>* PrepareAsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestAsset_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Requests for an Asset
    virtual ::grpc::Status RequestAsset(::grpc::ServerContext* context, const ::AssetName* request, ::Asset* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestAsset() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestAsset(::grpc::ServerContext* context, ::AssetName* request, ::grpc::ServerAsyncResponseWriter< ::Asset>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestAsset<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestAsset() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::AssetName, ::Asset>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::AssetName* request, ::Asset* response) { return this->RequestAsset(context, request, response); }));}
    void SetMessageAllocatorFor_RequestAsset(
        ::grpc::MessageAllocator< ::AssetName, ::Asset>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::AssetName, ::Asset>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestAsset(
      ::grpc::CallbackServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RequestAsset<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestAsset() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestAsset() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestAsset(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestAsset() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestAsset(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestAsset(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestAsset : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestAsset() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::AssetName, ::Asset>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::AssetName, ::Asset>* streamer) {
                       return this->StreamedRequestAsset(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestAsset() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestAsset(::grpc::ServerContext* /*context*/, const ::AssetName* /*request*/, ::Asset* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestAsset(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::AssetName,::Asset>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestAsset<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestAsset<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_assetstreamer_2eproto__INCLUDED
