// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scenestreamer.proto

#include "scenestreamer.pb.h"
#include "scenestreamer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SceneStreamer_method_names[] = {
  "/SceneStreamer/RequestScene",
};

std::unique_ptr< SceneStreamer::Stub> SceneStreamer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneStreamer::Stub> stub(new SceneStreamer::Stub(channel, options));
  return stub;
}

SceneStreamer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestScene_(SceneStreamer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::Scene>* SceneStreamer::Stub::RequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request) {
  return ::grpc::internal::ClientReaderFactory< ::Scene>::Create(channel_.get(), rpcmethod_RequestScene_, context, request);
}

void SceneStreamer::Stub::async::RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::grpc::ClientReadReactor< ::Scene>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::Scene>::Create(stub_->channel_.get(), stub_->rpcmethod_RequestScene_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::Scene>* SceneStreamer::Stub::AsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::Scene>::Create(channel_.get(), cq, rpcmethod_RequestScene_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::Scene>* SceneStreamer::Stub::PrepareAsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::Scene>::Create(channel_.get(), cq, rpcmethod_RequestScene_, context, request, false, nullptr);
}

SceneStreamer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneStreamer_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< SceneStreamer::Service, ::SceneIndex, ::Scene>(
          [](SceneStreamer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneIndex* req,
             ::grpc::ServerWriter<::Scene>* writer) {
               return service->RequestScene(ctx, req, writer);
             }, this)));
}

SceneStreamer::Service::~Service() {
}

::grpc::Status SceneStreamer::Service::RequestScene(::grpc::ServerContext* context, const ::SceneIndex* request, ::grpc::ServerWriter< ::Scene>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


