// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scenestreamer.proto
// Protobuf C++ Version: 5.29.3

#ifndef scenestreamer_2eproto_2epb_2eh
#define scenestreamer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scenestreamer_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scenestreamer_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scenestreamer_2eproto;
class Scene;
struct SceneDefaultTypeInternal;
extern SceneDefaultTypeInternal _Scene_default_instance_;
class SceneIndex;
struct SceneIndexDefaultTypeInternal;
extern SceneIndexDefaultTypeInternal _SceneIndex_default_instance_;
class Scene_Asset;
struct Scene_AssetDefaultTypeInternal;
extern Scene_AssetDefaultTypeInternal _Scene_Asset_default_instance_;
class Scene_Asset_Pos;
struct Scene_Asset_PosDefaultTypeInternal;
extern Scene_Asset_PosDefaultTypeInternal _Scene_Asset_Pos_default_instance_;
class Scene_Asset_Scale;
struct Scene_Asset_ScaleDefaultTypeInternal;
extern Scene_Asset_ScaleDefaultTypeInternal _Scene_Asset_Scale_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SceneIndex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SceneIndex) */ {
 public:
  inline SceneIndex() : SceneIndex(nullptr) {}
  ~SceneIndex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SceneIndex* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SceneIndex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SceneIndex(
      ::google::protobuf::internal::ConstantInitialized);

  inline SceneIndex(const SceneIndex& from) : SceneIndex(nullptr, from) {}
  inline SceneIndex(SceneIndex&& from) noexcept
      : SceneIndex(nullptr, std::move(from)) {}
  inline SceneIndex& operator=(const SceneIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneIndex& operator=(SceneIndex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneIndex* internal_default_instance() {
    return reinterpret_cast<const SceneIndex*>(
        &_SceneIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SceneIndex& a, SceneIndex& b) { a.Swap(&b); }
  inline void Swap(SceneIndex* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneIndex* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneIndex* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SceneIndex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SceneIndex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SceneIndex& from) { SceneIndex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SceneIndex* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SceneIndex"; }

 protected:
  explicit SceneIndex(::google::protobuf::Arena* arena);
  SceneIndex(::google::protobuf::Arena* arena, const SceneIndex& from);
  SceneIndex(::google::protobuf::Arena* arena, SceneIndex&& from) noexcept
      : SceneIndex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSceneidFieldNumber = 1,
  };
  // int32 sceneid = 1;
  void clear_sceneid() ;
  ::int32_t sceneid() const;
  void set_sceneid(::int32_t value);

  private:
  ::int32_t _internal_sceneid() const;
  void _internal_set_sceneid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SceneIndex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SceneIndex& from_msg);
    ::int32_t sceneid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};
// -------------------------------------------------------------------

class Scene_Asset_Scale final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Scene.Asset.Scale) */ {
 public:
  inline Scene_Asset_Scale() : Scene_Asset_Scale(nullptr) {}
  ~Scene_Asset_Scale() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scene_Asset_Scale* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scene_Asset_Scale));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scene_Asset_Scale(
      ::google::protobuf::internal::ConstantInitialized);

  inline Scene_Asset_Scale(const Scene_Asset_Scale& from) : Scene_Asset_Scale(nullptr, from) {}
  inline Scene_Asset_Scale(Scene_Asset_Scale&& from) noexcept
      : Scene_Asset_Scale(nullptr, std::move(from)) {}
  inline Scene_Asset_Scale& operator=(const Scene_Asset_Scale& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene_Asset_Scale& operator=(Scene_Asset_Scale&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene_Asset_Scale& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene_Asset_Scale* internal_default_instance() {
    return reinterpret_cast<const Scene_Asset_Scale*>(
        &_Scene_Asset_Scale_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Scene_Asset_Scale& a, Scene_Asset_Scale& b) { a.Swap(&b); }
  inline void Swap(Scene_Asset_Scale* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene_Asset_Scale* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene_Asset_Scale* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scene_Asset_Scale>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scene_Asset_Scale& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scene_Asset_Scale& from) { Scene_Asset_Scale::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scene_Asset_Scale* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Scene.Asset.Scale"; }

 protected:
  explicit Scene_Asset_Scale(::google::protobuf::Arena* arena);
  Scene_Asset_Scale(::google::protobuf::Arena* arena, const Scene_Asset_Scale& from);
  Scene_Asset_Scale(::google::protobuf::Arena* arena, Scene_Asset_Scale&& from) noexcept
      : Scene_Asset_Scale(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Scene.Asset.Scale)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Scene_Asset_Scale& from_msg);
    float x_;
    float y_;
    float z_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};
// -------------------------------------------------------------------

class Scene_Asset_Pos final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Scene.Asset.Pos) */ {
 public:
  inline Scene_Asset_Pos() : Scene_Asset_Pos(nullptr) {}
  ~Scene_Asset_Pos() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scene_Asset_Pos* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scene_Asset_Pos));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scene_Asset_Pos(
      ::google::protobuf::internal::ConstantInitialized);

  inline Scene_Asset_Pos(const Scene_Asset_Pos& from) : Scene_Asset_Pos(nullptr, from) {}
  inline Scene_Asset_Pos(Scene_Asset_Pos&& from) noexcept
      : Scene_Asset_Pos(nullptr, std::move(from)) {}
  inline Scene_Asset_Pos& operator=(const Scene_Asset_Pos& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene_Asset_Pos& operator=(Scene_Asset_Pos&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene_Asset_Pos& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene_Asset_Pos* internal_default_instance() {
    return reinterpret_cast<const Scene_Asset_Pos*>(
        &_Scene_Asset_Pos_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Scene_Asset_Pos& a, Scene_Asset_Pos& b) { a.Swap(&b); }
  inline void Swap(Scene_Asset_Pos* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene_Asset_Pos* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene_Asset_Pos* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scene_Asset_Pos>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scene_Asset_Pos& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scene_Asset_Pos& from) { Scene_Asset_Pos::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scene_Asset_Pos* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Scene.Asset.Pos"; }

 protected:
  explicit Scene_Asset_Pos(::google::protobuf::Arena* arena);
  Scene_Asset_Pos(::google::protobuf::Arena* arena, const Scene_Asset_Pos& from);
  Scene_Asset_Pos(::google::protobuf::Arena* arena, Scene_Asset_Pos&& from) noexcept
      : Scene_Asset_Pos(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Scene.Asset.Pos)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Scene_Asset_Pos& from_msg);
    float x_;
    float y_;
    float z_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};
// -------------------------------------------------------------------

class Scene_Asset final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Scene.Asset) */ {
 public:
  inline Scene_Asset() : Scene_Asset(nullptr) {}
  ~Scene_Asset() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scene_Asset* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scene_Asset));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scene_Asset(
      ::google::protobuf::internal::ConstantInitialized);

  inline Scene_Asset(const Scene_Asset& from) : Scene_Asset(nullptr, from) {}
  inline Scene_Asset(Scene_Asset&& from) noexcept
      : Scene_Asset(nullptr, std::move(from)) {}
  inline Scene_Asset& operator=(const Scene_Asset& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene_Asset& operator=(Scene_Asset&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene_Asset& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene_Asset* internal_default_instance() {
    return reinterpret_cast<const Scene_Asset*>(
        &_Scene_Asset_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Scene_Asset& a, Scene_Asset& b) { a.Swap(&b); }
  inline void Swap(Scene_Asset* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene_Asset* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene_Asset* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scene_Asset>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scene_Asset& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scene_Asset& from) { Scene_Asset::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scene_Asset* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Scene.Asset"; }

 protected:
  explicit Scene_Asset(::google::protobuf::Arena* arena);
  Scene_Asset(::google::protobuf::Arena* arena, const Scene_Asset& from);
  Scene_Asset(::google::protobuf::Arena* arena, Scene_Asset&& from) noexcept
      : Scene_Asset(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Pos = Scene_Asset_Pos;
  using Scale = Scene_Asset_Scale;

  // accessors -------------------------------------------------------
  enum : int {
    kObjdataFieldNumber = 3,
    kPosFieldNumber = 1,
    kScaleFieldNumber = 2,
  };
  // string objdata = 3;
  void clear_objdata() ;
  const std::string& objdata() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_objdata(Arg_&& arg, Args_... args);
  std::string* mutable_objdata();
  PROTOBUF_NODISCARD std::string* release_objdata();
  void set_allocated_objdata(std::string* value);

  private:
  const std::string& _internal_objdata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_objdata(
      const std::string& value);
  std::string* _internal_mutable_objdata();

  public:
  // .Scene.Asset.Pos pos = 1;
  bool has_pos() const;
  void clear_pos() ;
  const ::Scene_Asset_Pos& pos() const;
  PROTOBUF_NODISCARD ::Scene_Asset_Pos* release_pos();
  ::Scene_Asset_Pos* mutable_pos();
  void set_allocated_pos(::Scene_Asset_Pos* value);
  void unsafe_arena_set_allocated_pos(::Scene_Asset_Pos* value);
  ::Scene_Asset_Pos* unsafe_arena_release_pos();

  private:
  const ::Scene_Asset_Pos& _internal_pos() const;
  ::Scene_Asset_Pos* _internal_mutable_pos();

  public:
  // .Scene.Asset.Scale scale = 2;
  bool has_scale() const;
  void clear_scale() ;
  const ::Scene_Asset_Scale& scale() const;
  PROTOBUF_NODISCARD ::Scene_Asset_Scale* release_scale();
  ::Scene_Asset_Scale* mutable_scale();
  void set_allocated_scale(::Scene_Asset_Scale* value);
  void unsafe_arena_set_allocated_scale(::Scene_Asset_Scale* value);
  ::Scene_Asset_Scale* unsafe_arena_release_scale();

  private:
  const ::Scene_Asset_Scale& _internal_scale() const;
  ::Scene_Asset_Scale* _internal_mutable_scale();

  public:
  // @@protoc_insertion_point(class_scope:Scene.Asset)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 2,
      27, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Scene_Asset& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr objdata_;
    ::Scene_Asset_Pos* pos_;
    ::Scene_Asset_Scale* scale_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};
// -------------------------------------------------------------------

class Scene final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Scene) */ {
 public:
  inline Scene() : Scene(nullptr) {}
  ~Scene() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scene* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scene));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scene(
      ::google::protobuf::internal::ConstantInitialized);

  inline Scene(const Scene& from) : Scene(nullptr, from) {}
  inline Scene(Scene&& from) noexcept
      : Scene(nullptr, std::move(from)) {}
  inline Scene& operator=(const Scene& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene& operator=(Scene&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene* internal_default_instance() {
    return reinterpret_cast<const Scene*>(
        &_Scene_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(Scene& a, Scene& b) { a.Swap(&b); }
  inline void Swap(Scene* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scene>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scene& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scene& from) { Scene::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scene* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Scene"; }

 protected:
  explicit Scene(::google::protobuf::Arena* arena);
  Scene(::google::protobuf::Arena* arena, const Scene& from);
  Scene(::google::protobuf::Arena* arena, Scene&& from) noexcept
      : Scene(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Asset = Scene_Asset;

  // accessors -------------------------------------------------------
  enum : int {
    kAssetlistFieldNumber = 1,
  };
  // repeated .Scene.Asset assetlist = 1;
  int assetlist_size() const;
  private:
  int _internal_assetlist_size() const;

  public:
  void clear_assetlist() ;
  ::Scene_Asset* mutable_assetlist(int index);
  ::google::protobuf::RepeatedPtrField<::Scene_Asset>* mutable_assetlist();

  private:
  const ::google::protobuf::RepeatedPtrField<::Scene_Asset>& _internal_assetlist() const;
  ::google::protobuf::RepeatedPtrField<::Scene_Asset>* _internal_mutable_assetlist();
  public:
  const ::Scene_Asset& assetlist(int index) const;
  ::Scene_Asset* add_assetlist();
  const ::google::protobuf::RepeatedPtrField<::Scene_Asset>& assetlist() const;
  // @@protoc_insertion_point(class_scope:Scene)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Scene& from_msg);
    ::google::protobuf::RepeatedPtrField< ::Scene_Asset > assetlist_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SceneIndex

// int32 sceneid = 1;
inline void SceneIndex::clear_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_ = 0;
}
inline ::int32_t SceneIndex::sceneid() const {
  // @@protoc_insertion_point(field_get:SceneIndex.sceneid)
  return _internal_sceneid();
}
inline void SceneIndex::set_sceneid(::int32_t value) {
  _internal_set_sceneid(value);
  // @@protoc_insertion_point(field_set:SceneIndex.sceneid)
}
inline ::int32_t SceneIndex::_internal_sceneid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sceneid_;
}
inline void SceneIndex::_internal_set_sceneid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_ = value;
}

// -------------------------------------------------------------------

// Scene_Asset_Pos

// float x = 1;
inline void Scene_Asset_Pos::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float Scene_Asset_Pos::x() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Pos.x)
  return _internal_x();
}
inline void Scene_Asset_Pos::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Pos.x)
}
inline float Scene_Asset_Pos::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Scene_Asset_Pos::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Scene_Asset_Pos::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float Scene_Asset_Pos::y() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Pos.y)
  return _internal_y();
}
inline void Scene_Asset_Pos::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Pos.y)
}
inline float Scene_Asset_Pos::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Scene_Asset_Pos::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Scene_Asset_Pos::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline float Scene_Asset_Pos::z() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Pos.z)
  return _internal_z();
}
inline void Scene_Asset_Pos::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Pos.z)
}
inline float Scene_Asset_Pos::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Scene_Asset_Pos::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// Scene_Asset_Scale

// float x = 1;
inline void Scene_Asset_Scale::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float Scene_Asset_Scale::x() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Scale.x)
  return _internal_x();
}
inline void Scene_Asset_Scale::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Scale.x)
}
inline float Scene_Asset_Scale::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Scene_Asset_Scale::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Scene_Asset_Scale::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float Scene_Asset_Scale::y() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Scale.y)
  return _internal_y();
}
inline void Scene_Asset_Scale::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Scale.y)
}
inline float Scene_Asset_Scale::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Scene_Asset_Scale::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Scene_Asset_Scale::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline float Scene_Asset_Scale::z() const {
  // @@protoc_insertion_point(field_get:Scene.Asset.Scale.z)
  return _internal_z();
}
inline void Scene_Asset_Scale::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Scene.Asset.Scale.z)
}
inline float Scene_Asset_Scale::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Scene_Asset_Scale::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// Scene_Asset

// .Scene.Asset.Pos pos = 1;
inline bool Scene_Asset::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline void Scene_Asset::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Scene_Asset_Pos& Scene_Asset::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Scene_Asset_Pos* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::Scene_Asset_Pos&>(::_Scene_Asset_Pos_default_instance_);
}
inline const ::Scene_Asset_Pos& Scene_Asset::pos() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.Asset.pos)
  return _internal_pos();
}
inline void Scene_Asset::unsafe_arena_set_allocated_pos(::Scene_Asset_Pos* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::Scene_Asset_Pos*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Scene.Asset.pos)
}
inline ::Scene_Asset_Pos* Scene_Asset::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Scene_Asset_Pos* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Scene_Asset_Pos* Scene_Asset::unsafe_arena_release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.Asset.pos)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Scene_Asset_Pos* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::Scene_Asset_Pos* Scene_Asset::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Scene_Asset_Pos>(GetArena());
    _impl_.pos_ = reinterpret_cast<::Scene_Asset_Pos*>(p);
  }
  return _impl_.pos_;
}
inline ::Scene_Asset_Pos* Scene_Asset::mutable_pos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Scene_Asset_Pos* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:Scene.Asset.pos)
  return _msg;
}
inline void Scene_Asset::set_allocated_pos(::Scene_Asset_Pos* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.pos_ = reinterpret_cast<::Scene_Asset_Pos*>(value);
  // @@protoc_insertion_point(field_set_allocated:Scene.Asset.pos)
}

// .Scene.Asset.Scale scale = 2;
inline bool Scene_Asset::has_scale() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.scale_ != nullptr);
  return value;
}
inline void Scene_Asset::clear_scale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.scale_ != nullptr) _impl_.scale_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::Scene_Asset_Scale& Scene_Asset::_internal_scale() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Scene_Asset_Scale* p = _impl_.scale_;
  return p != nullptr ? *p : reinterpret_cast<const ::Scene_Asset_Scale&>(::_Scene_Asset_Scale_default_instance_);
}
inline const ::Scene_Asset_Scale& Scene_Asset::scale() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.Asset.scale)
  return _internal_scale();
}
inline void Scene_Asset::unsafe_arena_set_allocated_scale(::Scene_Asset_Scale* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.scale_);
  }
  _impl_.scale_ = reinterpret_cast<::Scene_Asset_Scale*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Scene.Asset.scale)
}
inline ::Scene_Asset_Scale* Scene_Asset::release_scale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Scene_Asset_Scale* released = _impl_.scale_;
  _impl_.scale_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Scene_Asset_Scale* Scene_Asset::unsafe_arena_release_scale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.Asset.scale)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Scene_Asset_Scale* temp = _impl_.scale_;
  _impl_.scale_ = nullptr;
  return temp;
}
inline ::Scene_Asset_Scale* Scene_Asset::_internal_mutable_scale() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.scale_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Scene_Asset_Scale>(GetArena());
    _impl_.scale_ = reinterpret_cast<::Scene_Asset_Scale*>(p);
  }
  return _impl_.scale_;
}
inline ::Scene_Asset_Scale* Scene_Asset::mutable_scale() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Scene_Asset_Scale* _msg = _internal_mutable_scale();
  // @@protoc_insertion_point(field_mutable:Scene.Asset.scale)
  return _msg;
}
inline void Scene_Asset::set_allocated_scale(::Scene_Asset_Scale* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.scale_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.scale_ = reinterpret_cast<::Scene_Asset_Scale*>(value);
  // @@protoc_insertion_point(field_set_allocated:Scene.Asset.scale)
}

// string objdata = 3;
inline void Scene_Asset::clear_objdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objdata_.ClearToEmpty();
}
inline const std::string& Scene_Asset::objdata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.Asset.objdata)
  return _internal_objdata();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene_Asset::set_objdata(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objdata_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.Asset.objdata)
}
inline std::string* Scene_Asset::mutable_objdata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_objdata();
  // @@protoc_insertion_point(field_mutable:Scene.Asset.objdata)
  return _s;
}
inline const std::string& Scene_Asset::_internal_objdata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objdata_.Get();
}
inline void Scene_Asset::_internal_set_objdata(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objdata_.Set(value, GetArena());
}
inline std::string* Scene_Asset::_internal_mutable_objdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.objdata_.Mutable( GetArena());
}
inline std::string* Scene_Asset::release_objdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.Asset.objdata)
  return _impl_.objdata_.Release();
}
inline void Scene_Asset::set_allocated_objdata(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objdata_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.objdata_.IsDefault()) {
    _impl_.objdata_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.Asset.objdata)
}

// -------------------------------------------------------------------

// Scene

// repeated .Scene.Asset assetlist = 1;
inline int Scene::_internal_assetlist_size() const {
  return _internal_assetlist().size();
}
inline int Scene::assetlist_size() const {
  return _internal_assetlist_size();
}
inline void Scene::clear_assetlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assetlist_.Clear();
}
inline ::Scene_Asset* Scene::mutable_assetlist(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Scene.assetlist)
  return _internal_mutable_assetlist()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Scene_Asset>* Scene::mutable_assetlist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Scene.assetlist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_assetlist();
}
inline const ::Scene_Asset& Scene::assetlist(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.assetlist)
  return _internal_assetlist().Get(index);
}
inline ::Scene_Asset* Scene::add_assetlist() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Scene_Asset* _add = _internal_mutable_assetlist()->Add();
  // @@protoc_insertion_point(field_add:Scene.assetlist)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Scene_Asset>& Scene::assetlist() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Scene.assetlist)
  return _internal_assetlist();
}
inline const ::google::protobuf::RepeatedPtrField<::Scene_Asset>&
Scene::_internal_assetlist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assetlist_;
}
inline ::google::protobuf::RepeatedPtrField<::Scene_Asset>*
Scene::_internal_mutable_assetlist() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.assetlist_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // scenestreamer_2eproto_2epb_2eh
