// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scenestreamer.proto
// Protobuf C++ Version: 5.29.3

#include "scenestreamer.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr msg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : strmsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR msg::msg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct msgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR msgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~msgDefaultTypeInternal() {}
  union {
    msg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 msgDefaultTypeInternal _msg_default_instance_;

inline constexpr SceneIndex::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sceneid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SceneIndex::SceneIndex(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneIndexDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneIndexDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneIndexDefaultTypeInternal() {}
  union {
    SceneIndex _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneIndexDefaultTypeInternal _SceneIndex_default_instance_;

inline constexpr Scene::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : asset1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        asset2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Scene::Scene(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SceneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SceneDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SceneDefaultTypeInternal() {}
  union {
    Scene _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SceneDefaultTypeInternal _Scene_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_scenestreamer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_scenestreamer_2eproto = nullptr;
const ::uint32_t
    TableStruct_scenestreamer_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SceneIndex, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SceneIndex, _impl_.sceneid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::msg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::msg, _impl_.strmsg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Scene, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Scene, _impl_.asset1_),
        PROTOBUF_FIELD_OFFSET(::Scene, _impl_.asset2_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::SceneIndex)},
        {9, -1, -1, sizeof(::msg)},
        {18, -1, -1, sizeof(::Scene)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_SceneIndex_default_instance_._instance,
    &::_msg_default_instance_._instance,
    &::_Scene_default_instance_._instance,
};
const char descriptor_table_protodef_scenestreamer_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023scenestreamer.proto\"\035\n\nSceneIndex\022\017\n\007s"
    "ceneid\030\001 \001(\005\"\025\n\003msg\022\016\n\006strmsg\030\001 \001(\t\"\'\n\005S"
    "cene\022\016\n\006asset1\030\001 \001(\014\022\016\n\006asset2\030\002 \001(\0142N\n\r"
    "SceneStreamer\022\'\n\014RequestScene\022\013.SceneInd"
    "ex\032\006.Scene\"\0000\001\022\024\n\004Ping\022\004.msg\032\004.msg\"\000b\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_scenestreamer_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_scenestreamer_2eproto = {
    false,
    false,
    204,
    descriptor_table_protodef_scenestreamer_2eproto,
    "scenestreamer.proto",
    &descriptor_table_scenestreamer_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_scenestreamer_2eproto::offsets,
    file_level_enum_descriptors_scenestreamer_2eproto,
    file_level_service_descriptors_scenestreamer_2eproto,
};
// ===================================================================

class SceneIndex::_Internal {
 public:
};

SceneIndex::SceneIndex(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SceneIndex)
}
SceneIndex::SceneIndex(
    ::google::protobuf::Arena* arena, const SceneIndex& from)
    : SceneIndex(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SceneIndex::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SceneIndex::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sceneid_ = {};
}
SceneIndex::~SceneIndex() {
  // @@protoc_insertion_point(destructor:SceneIndex)
  SharedDtor(*this);
}
inline void SceneIndex::SharedDtor(MessageLite& self) {
  SceneIndex& this_ = static_cast<SceneIndex&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SceneIndex::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SceneIndex(arena);
}
constexpr auto SceneIndex::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SceneIndex),
                                            alignof(SceneIndex));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SceneIndex::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SceneIndex_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SceneIndex::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SceneIndex>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SceneIndex::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SceneIndex>(), &SceneIndex::ByteSizeLong,
            &SceneIndex::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SceneIndex, _impl_._cached_size_),
        false,
    },
    &SceneIndex::kDescriptorMethods,
    &descriptor_table_scenestreamer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SceneIndex::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SceneIndex::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SceneIndex>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 sceneid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SceneIndex, _impl_.sceneid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SceneIndex, _impl_.sceneid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sceneid = 1;
    {PROTOBUF_FIELD_OFFSET(SceneIndex, _impl_.sceneid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SceneIndex::Clear() {
// @@protoc_insertion_point(message_clear_start:SceneIndex)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sceneid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SceneIndex::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SceneIndex& this_ = static_cast<const SceneIndex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SceneIndex::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SceneIndex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SceneIndex)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 sceneid = 1;
          if (this_._internal_sceneid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_sceneid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SceneIndex)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SceneIndex::ByteSizeLong(const MessageLite& base) {
          const SceneIndex& this_ = static_cast<const SceneIndex&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SceneIndex::ByteSizeLong() const {
          const SceneIndex& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SceneIndex)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 sceneid = 1;
            if (this_._internal_sceneid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sceneid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SceneIndex::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SceneIndex*>(&to_msg);
  auto& from = static_cast<const SceneIndex&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SceneIndex)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sceneid() != 0) {
    _this->_impl_.sceneid_ = from._impl_.sceneid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SceneIndex::CopyFrom(const SceneIndex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SceneIndex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SceneIndex::InternalSwap(SceneIndex* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sceneid_, other->_impl_.sceneid_);
}

::google::protobuf::Metadata SceneIndex::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class msg::_Internal {
 public:
};

msg::msg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg)
}
inline PROTOBUF_NDEBUG_INLINE msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::msg& from_msg)
      : strmsg_(arena, from.strmsg_),
        _cached_size_{0} {}

msg::msg(
    ::google::protobuf::Arena* arena,
    const msg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  msg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:msg)
}
inline PROTOBUF_NDEBUG_INLINE msg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : strmsg_(arena),
        _cached_size_{0} {}

inline void msg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
msg::~msg() {
  // @@protoc_insertion_point(destructor:msg)
  SharedDtor(*this);
}
inline void msg::SharedDtor(MessageLite& self) {
  msg& this_ = static_cast<msg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.strmsg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* msg::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) msg(arena);
}
constexpr auto msg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(msg),
                                            alignof(msg));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull msg::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_msg_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &msg::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<msg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &msg::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<msg>(), &msg::ByteSizeLong,
            &msg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(msg, _impl_._cached_size_),
        false,
    },
    &msg::kDescriptorMethods,
    &descriptor_table_scenestreamer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* msg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 18, 2> msg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::msg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string strmsg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(msg, _impl_.strmsg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string strmsg = 1;
    {PROTOBUF_FIELD_OFFSET(msg, _impl_.strmsg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\3\6\0\0\0\0\0\0"
    "msg"
    "strmsg"
  }},
};

PROTOBUF_NOINLINE void msg::Clear() {
// @@protoc_insertion_point(message_clear_start:msg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.strmsg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* msg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const msg& this_ = static_cast<const msg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* msg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const msg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:msg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string strmsg = 1;
          if (!this_._internal_strmsg().empty()) {
            const std::string& _s = this_._internal_strmsg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "msg.strmsg");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:msg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t msg::ByteSizeLong(const MessageLite& base) {
          const msg& this_ = static_cast<const msg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t msg::ByteSizeLong() const {
          const msg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:msg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string strmsg = 1;
            if (!this_._internal_strmsg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_strmsg());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void msg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<msg*>(&to_msg);
  auto& from = static_cast<const msg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_strmsg().empty()) {
    _this->_internal_set_strmsg(from._internal_strmsg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void msg::CopyFrom(const msg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void msg::InternalSwap(msg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.strmsg_, &other->_impl_.strmsg_, arena);
}

::google::protobuf::Metadata msg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Scene::_Internal {
 public:
};

Scene::Scene(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Scene)
}
inline PROTOBUF_NDEBUG_INLINE Scene::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Scene& from_msg)
      : asset1_(arena, from.asset1_),
        asset2_(arena, from.asset2_),
        _cached_size_{0} {}

Scene::Scene(
    ::google::protobuf::Arena* arena,
    const Scene& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Scene* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Scene)
}
inline PROTOBUF_NDEBUG_INLINE Scene::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : asset1_(arena),
        asset2_(arena),
        _cached_size_{0} {}

inline void Scene::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Scene::~Scene() {
  // @@protoc_insertion_point(destructor:Scene)
  SharedDtor(*this);
}
inline void Scene::SharedDtor(MessageLite& self) {
  Scene& this_ = static_cast<Scene&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.asset1_.Destroy();
  this_._impl_.asset2_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Scene::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Scene(arena);
}
constexpr auto Scene::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Scene),
                                            alignof(Scene));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Scene::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Scene_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Scene::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Scene>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Scene::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Scene>(), &Scene::ByteSizeLong,
            &Scene::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Scene, _impl_._cached_size_),
        false,
    },
    &Scene::kDescriptorMethods,
    &descriptor_table_scenestreamer_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Scene::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Scene::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Scene>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes asset2 = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Scene, _impl_.asset2_)}},
    // bytes asset1 = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Scene, _impl_.asset1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes asset1 = 1;
    {PROTOBUF_FIELD_OFFSET(Scene, _impl_.asset1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes asset2 = 2;
    {PROTOBUF_FIELD_OFFSET(Scene, _impl_.asset2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Scene::Clear() {
// @@protoc_insertion_point(message_clear_start:Scene)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.asset1_.ClearToEmpty();
  _impl_.asset2_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Scene::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Scene& this_ = static_cast<const Scene&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Scene::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Scene& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Scene)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bytes asset1 = 1;
          if (!this_._internal_asset1().empty()) {
            const std::string& _s = this_._internal_asset1();
            target = stream->WriteBytesMaybeAliased(1, _s, target);
          }

          // bytes asset2 = 2;
          if (!this_._internal_asset2().empty()) {
            const std::string& _s = this_._internal_asset2();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Scene)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Scene::ByteSizeLong(const MessageLite& base) {
          const Scene& this_ = static_cast<const Scene&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Scene::ByteSizeLong() const {
          const Scene& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Scene)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes asset1 = 1;
            if (!this_._internal_asset1().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_asset1());
            }
            // bytes asset2 = 2;
            if (!this_._internal_asset2().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_asset2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Scene::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Scene*>(&to_msg);
  auto& from = static_cast<const Scene&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Scene)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_asset1().empty()) {
    _this->_internal_set_asset1(from._internal_asset1());
  }
  if (!from._internal_asset2().empty()) {
    _this->_internal_set_asset2(from._internal_asset2());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Scene::CopyFrom(const Scene& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Scene)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Scene::InternalSwap(Scene* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.asset1_, &other->_impl_.asset1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.asset2_, &other->_impl_.asset2_, arena);
}

::google::protobuf::Metadata Scene::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_scenestreamer_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
