// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scenestreamer.proto
#ifndef GRPC_scenestreamer_2eproto__INCLUDED
#define GRPC_scenestreamer_2eproto__INCLUDED

#include "scenestreamer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

// The scene streamer service definition.
class SceneStreamer final {
 public:
  static constexpr char const* service_full_name() {
    return "SceneStreamer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Requests for a scene
    virtual ::grpc::Status RequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::Scene* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Scene>> AsyncRequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Scene>>(AsyncRequestSceneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Scene>> PrepareAsyncRequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Scene>>(PrepareAsyncRequestSceneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Requests for a scene
      virtual void RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Scene>* AsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Scene>* PrepareAsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::Scene* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Scene>> AsyncRequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Scene>>(AsyncRequestSceneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Scene>> PrepareAsyncRequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Scene>>(PrepareAsyncRequestSceneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, std::function<void(::grpc::Status)>) override;
      void RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Scene>* AsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Scene>* PrepareAsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RequestScene_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Requests for a scene
    virtual ::grpc::Status RequestScene(::grpc::ServerContext* context, const ::SceneIndex* request, ::Scene* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RequestScene() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestScene(::grpc::ServerContext* context, ::SceneIndex* request, ::grpc::ServerAsyncResponseWriter< ::Scene>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RequestScene<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RequestScene() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SceneIndex, ::Scene>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SceneIndex* request, ::Scene* response) { return this->RequestScene(context, request, response); }));}
    void SetMessageAllocatorFor_RequestScene(
        ::grpc::MessageAllocator< ::SceneIndex, ::Scene>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SceneIndex, ::Scene>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestScene(
      ::grpc::CallbackServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RequestScene<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RequestScene() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RequestScene() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRequestScene(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RequestScene() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RequestScene(context, request, response); }));
    }
    ~WithRawCallbackMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RequestScene(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RequestScene : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RequestScene() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SceneIndex, ::Scene>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SceneIndex, ::Scene>* streamer) {
                       return this->StreamedRequestScene(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RequestScene() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RequestScene(::grpc::ServerContext* /*context*/, const ::SceneIndex* /*request*/, ::Scene* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRequestScene(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SceneIndex,::Scene>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RequestScene<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RequestScene<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_scenestreamer_2eproto__INCLUDED
