// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: scenestreamer.proto
// Protobuf C++ Version: 5.29.3

#ifndef scenestreamer_2eproto_2epb_2eh
#define scenestreamer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_scenestreamer_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_scenestreamer_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_scenestreamer_2eproto;
class Scene;
struct SceneDefaultTypeInternal;
extern SceneDefaultTypeInternal _Scene_default_instance_;
class SceneIndex;
struct SceneIndexDefaultTypeInternal;
extern SceneIndexDefaultTypeInternal _SceneIndex_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SceneIndex final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SceneIndex) */ {
 public:
  inline SceneIndex() : SceneIndex(nullptr) {}
  ~SceneIndex() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SceneIndex* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SceneIndex));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SceneIndex(
      ::google::protobuf::internal::ConstantInitialized);

  inline SceneIndex(const SceneIndex& from) : SceneIndex(nullptr, from) {}
  inline SceneIndex(SceneIndex&& from) noexcept
      : SceneIndex(nullptr, std::move(from)) {}
  inline SceneIndex& operator=(const SceneIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline SceneIndex& operator=(SceneIndex&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SceneIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const SceneIndex* internal_default_instance() {
    return reinterpret_cast<const SceneIndex*>(
        &_SceneIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SceneIndex& a, SceneIndex& b) { a.Swap(&b); }
  inline void Swap(SceneIndex* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SceneIndex* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SceneIndex* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SceneIndex>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SceneIndex& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SceneIndex& from) { SceneIndex::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SceneIndex* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SceneIndex"; }

 protected:
  explicit SceneIndex(::google::protobuf::Arena* arena);
  SceneIndex(::google::protobuf::Arena* arena, const SceneIndex& from);
  SceneIndex(::google::protobuf::Arena* arena, SceneIndex&& from) noexcept
      : SceneIndex(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSceneidFieldNumber = 1,
  };
  // int32 sceneid = 1;
  void clear_sceneid() ;
  ::int32_t sceneid() const;
  void set_sceneid(::int32_t value);

  private:
  ::int32_t _internal_sceneid() const;
  void _internal_set_sceneid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SceneIndex)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SceneIndex& from_msg);
    ::int32_t sceneid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};
// -------------------------------------------------------------------

class Scene final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Scene) */ {
 public:
  inline Scene() : Scene(nullptr) {}
  ~Scene() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Scene* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Scene));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Scene(
      ::google::protobuf::internal::ConstantInitialized);

  inline Scene(const Scene& from) : Scene(nullptr, from) {}
  inline Scene(Scene&& from) noexcept
      : Scene(nullptr, std::move(from)) {}
  inline Scene& operator=(const Scene& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scene& operator=(Scene&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scene& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scene* internal_default_instance() {
    return reinterpret_cast<const Scene*>(
        &_Scene_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Scene& a, Scene& b) { a.Swap(&b); }
  inline void Swap(Scene* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scene* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scene* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Scene>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Scene& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Scene& from) { Scene::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Scene* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Scene"; }

 protected:
  explicit Scene(::google::protobuf::Arena* arena);
  Scene(::google::protobuf::Arena* arena, const Scene& from);
  Scene(::google::protobuf::Arena* arena, Scene&& from) noexcept
      : Scene(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAsset1FieldNumber = 1,
    kAsset2FieldNumber = 2,
    kAsset3FieldNumber = 3,
    kAsset4FieldNumber = 4,
    kAsset5FieldNumber = 5,
  };
  // bytes asset1 = 1;
  void clear_asset1() ;
  const std::string& asset1() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset1(Arg_&& arg, Args_... args);
  std::string* mutable_asset1();
  PROTOBUF_NODISCARD std::string* release_asset1();
  void set_allocated_asset1(std::string* value);

  private:
  const std::string& _internal_asset1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset1(
      const std::string& value);
  std::string* _internal_mutable_asset1();

  public:
  // bytes asset2 = 2;
  void clear_asset2() ;
  const std::string& asset2() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset2(Arg_&& arg, Args_... args);
  std::string* mutable_asset2();
  PROTOBUF_NODISCARD std::string* release_asset2();
  void set_allocated_asset2(std::string* value);

  private:
  const std::string& _internal_asset2() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset2(
      const std::string& value);
  std::string* _internal_mutable_asset2();

  public:
  // bytes asset3 = 3;
  void clear_asset3() ;
  const std::string& asset3() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset3(Arg_&& arg, Args_... args);
  std::string* mutable_asset3();
  PROTOBUF_NODISCARD std::string* release_asset3();
  void set_allocated_asset3(std::string* value);

  private:
  const std::string& _internal_asset3() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset3(
      const std::string& value);
  std::string* _internal_mutable_asset3();

  public:
  // bytes asset4 = 4;
  void clear_asset4() ;
  const std::string& asset4() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset4(Arg_&& arg, Args_... args);
  std::string* mutable_asset4();
  PROTOBUF_NODISCARD std::string* release_asset4();
  void set_allocated_asset4(std::string* value);

  private:
  const std::string& _internal_asset4() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset4(
      const std::string& value);
  std::string* _internal_mutable_asset4();

  public:
  // bytes asset5 = 5;
  void clear_asset5() ;
  const std::string& asset5() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_asset5(Arg_&& arg, Args_... args);
  std::string* mutable_asset5();
  PROTOBUF_NODISCARD std::string* release_asset5();
  void set_allocated_asset5(std::string* value);

  private:
  const std::string& _internal_asset5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset5(
      const std::string& value);
  std::string* _internal_mutable_asset5();

  public:
  // @@protoc_insertion_point(class_scope:Scene)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Scene& from_msg);
    ::google::protobuf::internal::ArenaStringPtr asset1_;
    ::google::protobuf::internal::ArenaStringPtr asset2_;
    ::google::protobuf::internal::ArenaStringPtr asset3_;
    ::google::protobuf::internal::ArenaStringPtr asset4_;
    ::google::protobuf::internal::ArenaStringPtr asset5_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_scenestreamer_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SceneIndex

// int32 sceneid = 1;
inline void SceneIndex::clear_sceneid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_ = 0;
}
inline ::int32_t SceneIndex::sceneid() const {
  // @@protoc_insertion_point(field_get:SceneIndex.sceneid)
  return _internal_sceneid();
}
inline void SceneIndex::set_sceneid(::int32_t value) {
  _internal_set_sceneid(value);
  // @@protoc_insertion_point(field_set:SceneIndex.sceneid)
}
inline ::int32_t SceneIndex::_internal_sceneid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sceneid_;
}
inline void SceneIndex::_internal_set_sceneid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sceneid_ = value;
}

// -------------------------------------------------------------------

// Scene

// bytes asset1 = 1;
inline void Scene::clear_asset1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset1_.ClearToEmpty();
}
inline const std::string& Scene::asset1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.asset1)
  return _internal_asset1();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene::set_asset1(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset1_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.asset1)
}
inline std::string* Scene::mutable_asset1() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset1();
  // @@protoc_insertion_point(field_mutable:Scene.asset1)
  return _s;
}
inline const std::string& Scene::_internal_asset1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset1_.Get();
}
inline void Scene::_internal_set_asset1(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset1_.Set(value, GetArena());
}
inline std::string* Scene::_internal_mutable_asset1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset1_.Mutable( GetArena());
}
inline std::string* Scene::release_asset1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.asset1)
  return _impl_.asset1_.Release();
}
inline void Scene::set_allocated_asset1(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset1_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset1_.IsDefault()) {
    _impl_.asset1_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.asset1)
}

// bytes asset2 = 2;
inline void Scene::clear_asset2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset2_.ClearToEmpty();
}
inline const std::string& Scene::asset2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.asset2)
  return _internal_asset2();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene::set_asset2(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset2_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.asset2)
}
inline std::string* Scene::mutable_asset2() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset2();
  // @@protoc_insertion_point(field_mutable:Scene.asset2)
  return _s;
}
inline const std::string& Scene::_internal_asset2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset2_.Get();
}
inline void Scene::_internal_set_asset2(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset2_.Set(value, GetArena());
}
inline std::string* Scene::_internal_mutable_asset2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset2_.Mutable( GetArena());
}
inline std::string* Scene::release_asset2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.asset2)
  return _impl_.asset2_.Release();
}
inline void Scene::set_allocated_asset2(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset2_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset2_.IsDefault()) {
    _impl_.asset2_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.asset2)
}

// bytes asset3 = 3;
inline void Scene::clear_asset3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset3_.ClearToEmpty();
}
inline const std::string& Scene::asset3() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.asset3)
  return _internal_asset3();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene::set_asset3(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset3_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.asset3)
}
inline std::string* Scene::mutable_asset3() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset3();
  // @@protoc_insertion_point(field_mutable:Scene.asset3)
  return _s;
}
inline const std::string& Scene::_internal_asset3() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset3_.Get();
}
inline void Scene::_internal_set_asset3(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset3_.Set(value, GetArena());
}
inline std::string* Scene::_internal_mutable_asset3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset3_.Mutable( GetArena());
}
inline std::string* Scene::release_asset3() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.asset3)
  return _impl_.asset3_.Release();
}
inline void Scene::set_allocated_asset3(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset3_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset3_.IsDefault()) {
    _impl_.asset3_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.asset3)
}

// bytes asset4 = 4;
inline void Scene::clear_asset4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset4_.ClearToEmpty();
}
inline const std::string& Scene::asset4() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.asset4)
  return _internal_asset4();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene::set_asset4(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset4_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.asset4)
}
inline std::string* Scene::mutable_asset4() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset4();
  // @@protoc_insertion_point(field_mutable:Scene.asset4)
  return _s;
}
inline const std::string& Scene::_internal_asset4() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset4_.Get();
}
inline void Scene::_internal_set_asset4(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset4_.Set(value, GetArena());
}
inline std::string* Scene::_internal_mutable_asset4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset4_.Mutable( GetArena());
}
inline std::string* Scene::release_asset4() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.asset4)
  return _impl_.asset4_.Release();
}
inline void Scene::set_allocated_asset4(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset4_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset4_.IsDefault()) {
    _impl_.asset4_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.asset4)
}

// bytes asset5 = 5;
inline void Scene::clear_asset5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset5_.ClearToEmpty();
}
inline const std::string& Scene::asset5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Scene.asset5)
  return _internal_asset5();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Scene::set_asset5(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset5_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Scene.asset5)
}
inline std::string* Scene::mutable_asset5() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_asset5();
  // @@protoc_insertion_point(field_mutable:Scene.asset5)
  return _s;
}
inline const std::string& Scene::_internal_asset5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.asset5_.Get();
}
inline void Scene::_internal_set_asset5(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset5_.Set(value, GetArena());
}
inline std::string* Scene::_internal_mutable_asset5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.asset5_.Mutable( GetArena());
}
inline std::string* Scene::release_asset5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Scene.asset5)
  return _impl_.asset5_.Release();
}
inline void Scene::set_allocated_asset5(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.asset5_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.asset5_.IsDefault()) {
    _impl_.asset5_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Scene.asset5)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // scenestreamer_2eproto_2epb_2eh
