syntax = "proto3";

// The asset streamer service definition.
service AssetStreamer {
	// Requests for an Asset
	rpc RequestAsset (AssetName) returns (Asset) {}
}

// The request message containing the asset's name.
message AssetName {
	string name = 1;
}

// The response message containing the transforms and obj data
message Asset {
	message Pos {
		float x = 1;
		float y = 2;
		float z = 3;
	};

	message Scale {
		float x = 1;
		float y = 2;
		float z = 3;
	};

	Pos pos = 1;			//Local position of the object
	Scale scale = 2;		//Local scale of the object
	string objdata = 3;		//.obj as plaintext
	
}
