// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: assetstreamer.proto

#include "assetstreamer.pb.h"
#include "assetstreamer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* AssetStreamer_method_names[] = {
  "/AssetStreamer/RequestAsset",
};

std::unique_ptr< AssetStreamer::Stub> AssetStreamer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AssetStreamer::Stub> stub(new AssetStreamer::Stub(channel, options));
  return stub;
}

AssetStreamer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestAsset_(AssetStreamer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AssetStreamer::Stub::RequestAsset(::grpc::ClientContext* context, const ::AssetName& request, ::Asset* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AssetName, ::Asset, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestAsset_, context, request, response);
}

void AssetStreamer::Stub::async::RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AssetName, ::Asset, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestAsset_, context, request, response, std::move(f));
}

void AssetStreamer::Stub::async::RequestAsset(::grpc::ClientContext* context, const ::AssetName* request, ::Asset* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestAsset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Asset>* AssetStreamer::Stub::PrepareAsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Asset, ::AssetName, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestAsset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Asset>* AssetStreamer::Stub::AsyncRequestAssetRaw(::grpc::ClientContext* context, const ::AssetName& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestAssetRaw(context, request, cq);
  result->StartCall();
  return result;
}

AssetStreamer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetStreamer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetStreamer::Service, ::AssetName, ::Asset, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetStreamer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AssetName* req,
             ::Asset* resp) {
               return service->RequestAsset(ctx, req, resp);
             }, this)));
}

AssetStreamer::Service::~Service() {
}

::grpc::Status AssetStreamer::Service::RequestAsset(::grpc::ServerContext* context, const ::AssetName* request, ::Asset* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


