// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: scenestreamer.proto

#include "scenestreamer.pb.h"
#include "scenestreamer.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* SceneStreamer_method_names[] = {
  "/SceneStreamer/RequestScene",
};

std::unique_ptr< SceneStreamer::Stub> SceneStreamer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SceneStreamer::Stub> stub(new SceneStreamer::Stub(channel, options));
  return stub;
}

SceneStreamer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RequestScene_(SceneStreamer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SceneStreamer::Stub::RequestScene(::grpc::ClientContext* context, const ::SceneIndex& request, ::Scene* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SceneIndex, ::Scene, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RequestScene_, context, request, response);
}

void SceneStreamer::Stub::async::RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SceneIndex, ::Scene, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestScene_, context, request, response, std::move(f));
}

void SceneStreamer::Stub::async::RequestScene(::grpc::ClientContext* context, const ::SceneIndex* request, ::Scene* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RequestScene_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Scene>* SceneStreamer::Stub::PrepareAsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Scene, ::SceneIndex, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RequestScene_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Scene>* SceneStreamer::Stub::AsyncRequestSceneRaw(::grpc::ClientContext* context, const ::SceneIndex& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRequestSceneRaw(context, request, cq);
  result->StartCall();
  return result;
}

SceneStreamer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SceneStreamer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SceneStreamer::Service, ::SceneIndex, ::Scene, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SceneStreamer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SceneIndex* req,
             ::Scene* resp) {
               return service->RequestScene(ctx, req, resp);
             }, this)));
}

SceneStreamer::Service::~Service() {
}

::grpc::Status SceneStreamer::Service::RequestScene(::grpc::ServerContext* context, const ::SceneIndex* request, ::Scene* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


